### ISSUE TITLE
Service Worker Error

### ISSUE THREAD

**Issue by ayumihamsaki** [GoogleChrome/sw-toolbox#104] opened 2016-03-27 22:38 UTC
Hello,

Getting lots of errors all related to CORS. After 3 days of looking for the problem, I have found the problem to be this header:

< meta http -equiv =" Accept-CH" content=" DPR, Viewport-Width, Width" / >

Not sure why but it does not work with service worker and produces many errors. For example I was using sw-toolbox and linking to some javascript files on cdnjs.com and some fonts via google fonts api, both started displaying messages of error 405 and cors problems.

e.g.

Failed to load resource: the server responded with a status of 405 (Not Allowed)

Fetch API cannot load https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.6/hammer.min.js. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://example.com' is therefore not allowed access. The response had HTTP status code 405. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

The FetchEvent for "https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.6/hammer.min.js" resulted in a network error response: the promise was rejected.

undefined:1 Uncaught (in promise) TypeError: Failed to fetch(…)

When I remove this meta header all problems disappear and when add it to the head section errors come back.

Conclusion: This header and service worker do not work together and give false errors. Also I am using Google Chrome version 51.0.2687.0 dev-m (64-bit) and Google Canary Version 51.0.2692.0 canary (64-bit). Both give these false errors with this meta header.

p.s. Just tested in Firefox seems to be ok so I guess its Google's browsers that have the error.

**Comment by gauntface** [comment] 2016-04-20 13:25
do you have an example project we can look at?

The problems you are highlighting regarding CORs is essentially saying you are requesting files that your domain isn't allowed to read for security reasons.

This shouldn't be affected by the meta tag unless you have one that manipulates the base url (in which case I'm not sure what the expected or correct behaviour would be).

**Comment by gauntface** [comment] 2016-04-27 18:20
I'm going to close this, please do re-open this if you can share an example, there are a few people hitting CORs issues, so would be good to find an example that we can reproduce.

Sidenote: I've noticed in some versions of Firefox, requests to other origins don't go through the service worker, which might explain why it's only in Chrome at the moment.

**Closed by gauntface** 2016-04-27 18:20 UTC

**Comment by Enalmada** [comment] 2017-06-01 16:26
When you copy a link from [cdnjs](https://cdnjs.com/libraries/twitter-bootstrap), it has an option to give you [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) in the link.

I just added integrity and crossorigin to my bootstrap link going from this:
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" />`
to this:
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha256-rr9hHBQ43H7HSOmmNkxzQGazS/Khx+L8ZRHteEY1tQ4=" crossorigin="anonymous" />`

And am now getting this error in the chrome console and the page fails:

```
The FetchEvent for "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" resulted in a network error response: an "opaque" response was used for a request whose type is not no-cors

GET https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css net::ERR_FAILED
```

**Comment by jeffposnick** [comment] 2017-06-02 20:27
What does your runtime caching configuration look like? How does the `bootstrap.min.css` end up getting added to your cache?

**Comment by Enalmada** [comment] 2017-06-02 22:41
This is what I think is the relevant section I am using to catch all my cdn assets:
```
    global.toolbox.router.get('/(.*)', global.toolbox.cacheFirst, {
        cache: {
            name: CURRENT_CACHES.cdnjs,
            maxEntries: 100,
        },
        origin: /\.cloudflare\.com$/
    });
```

(I can provide the whole service-worker file if that helps)

**Comment by jeffposnick** [comment] 2017-06-05 21:23
I attempted to reproduce what you're seeing using the sample code you provided:

https://rawgit.com/jeffposnick/f77a0ed74939a011ce23b6cba4349491/raw/b9071742eb59393dfff5915da8cddbe99a2268bb/index.html

I'm seeing the cached response for the CSS being used by the page without issue. Do you see anything different about what you're doing compared to what's in that reproduction?

**Comment by Enalmada** [comment] 2017-06-05 22:42
What you did looks comparable....and putting the integrity and crossorigin back on mine I can't reproduce it anymore.  It seemed consistently reproducible when I posted so I am scratching my head.  I will leave the SRI in and see if the message ever comes back.  Thanks for looking into it.

**Comment by jeffposnick** [comment] 2017-06-06 14:36
You probably had an old copy cached from a time you were experimenting without those attributes, and since you're using a `cacheFirst` policy, that ended up being used indefinitely.

Testing in a Chrome Incognito window is always a good thing, and you obviously need to be particularly careful when using `cacheFirst`.

**Comment by albandaft** [comment] 2017-07-19 14:34
I am getting on chrome MAC this error:
`resulted in a network error response: the promise was rejected`
and 
`Uncaught (in promise) TypeError: Failed to fetch`
And the code in the service worker is quite simple:
```
self.addEventListener('fetch', event => {
    if(event.request.method === 'GET') {
       if(event.request.url.startsWith(self.location.origin)) {
            event.respondWith(fetch(event.request));
        }
    }
});
```

**Comment by farhaan008** [comment] 2019-06-27 07:56
Hi @albandaft, facing the same issue, Does the above solution work?

**Comment by AlexBorsody** [comment] 2019-12-25 17:21
Also think I this is due to the `integrity` and `crossorigin` tag implementing the security feature [Subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity).

**Comment by Shimon42** [comment] 2021-04-04 23:35
Just faced the same issue as @farhaan008 for so long
adding "." to the cache.addAll array solved my problem 
I think it's because it is the  "start_url" in my manifest.json file

here is my service_worker.js

```
self.addEventListener('install', function(e) {
 e.waitUntil(
   caches.open(...).then(function(cache) {
     return cache.addAll([
	".",
	...
     ]);
   })
 );
});

self.addEventListener('fetch', function(event) {
 event.respondWith(
  caches.match(event.request).then(function(response) {
 	 return response || fetch(event.request);
  }, function(err) {
 	 // registration failed :(
 	 console.log('ServiceWorker registration failed: ', err);
  })
 );
});
```

Hope it will help ✌️
